### ISSUE TITLE
I made an Elm Architecture-like example in React

### ISSUE THREAD

**Issue by gaearon** [elm-guides/elm-for-js#8]
Just built [this](http://gaearon.github.io/react-elmish-example/) today to better understand Elm Architecture.
Feel free to close the issue—or to link to my project if you like it.

**Comment by gaearon** [comment]
Closing for the lack of interest.

**Comment by jamischarles** [comment]
Sorry Dan. Was gonna write a comment tomorrow. Will still try to.
